export const SOCIAL_NETWORK_INITIATE_FETCH_ALL = "SOCIAL_NETWORK_INITIATE_FETCH_ALL";
export const SOCIAL_NETWORK_SET_ITEMS = "SOCIAL_NETWORK_SET_ITEMS";
export const SOCIAL_NETWORK_INITIATE_SAVE = "SOCIAL_NETWORK_INITIATE_SAVE";
export const SOCIAL_NETWORK_SET_SHOW_ALERT = "SOCIAL_NETWORK_SET_SHOW_ALERT";
export const SOCIAL_NETWORK_SET_IS_SAVED = "SOCIAL_NETWORK_SET_IS_SAVED";
export const SOCIAL_NETWORK_SET_MESSAGE = "SOCIAL_NETWORK_SET_MESSAGE";
