export const POST_INITIATE_STORE = "POST_INITIATE_STORE";
export const POST_INITIATE_UPDATE = "POST_INITIATE_UPDATE";

export const POST_FETCH_ALL = "POST_FETCH_ALL";
export const POST_SET_ALL = "POST_SET_ALL";

export const POST_INITIATE_FRONT_FETCH_ALL = "POST_INITIATE_FRONT_FETCH_ALL";
export const POST_SET_FRONT_ALL = "POST_SET_FRONT_ALL";
export const POST_FRONT_SET_SEARCH = "POST_FRONT_SET_SEARCH";
export const POST_FRONT_SET_PAGE = "POST_FRONT_SET_PAGE";
export const POST_FRONT_SET_ROWS = "POST_FRONT_SET_ROWS";

export const POST_INITIATE_FRONT_FETCH_ONE = "POST_INITIATE_FRONT_FETCH_ONE";
export const POST_SET_FRONT_ONE = "POST_SET_FRONT_ONE";

export const POST_INITIATE_DELETE = "POST_INITIATE_DELETE";

export const POST_FORM_SET_ERROR = "POST_FORM_SET_ERROR";
export const POST_FORM_SET_LOADING = "POST_FORM_SET_LOADING";

export const POST_SET_FORM_CLOSE = "POST_SET_FORM_CLOSE";
