export const TEST_SET_MOBILE_NUMBER = "TEST_SET_MOBILE_NUMBER";

export const TEST_SEND_CODE = "TEST_SEND_CODE";

export const TEST_VERIFY_CODE = "TEST_VERIFY_CODE";

export const TEST_IS_VERIFIED = "TEST_IS_VERIFIED";

export const TEST_FETCH_QUESTION = "TEST_FETCH_QUESTION";
//
export const TEST_SET_STEP = "TEST_SET_STEP";

export const TEST_SET_QUESTION = "TEST_SET_QUESTION";

export const TEST_SET_LOADING = "TEST_SET_LOADING";

export const TEST_SET_ERROR = "TEST_SET_ERROR";

export const TEST_SET_SHOW_ALERT = "TEST_SET_SHOW_ALERT";

export const TEST_SET_MESSAGE_TYPE = "TEST_SET_MESSAGE_TYPE";

export const TEST_SET_MESSAGE = "TEST_SET_MESSAGE";
