export const TEST_SET_MOBILE_NUMBER = "TEST_SET_MOBILE_NUMBER";

export const TEST_INITIATE_FETCH = "TEST_INITIATE_FETCH";

export const TEST_SAVE_QUESTION = "TEST_SAVE_QUESTION";

export const CONFIG_SET_LOADING = "CONFIG_SET_LOADING";

export const CONFIG_SET_SHOW_ALERT = "CONFIG_SET_SHOW_ALERT";

export const CONFIG_SET_IS_SAVED = "CONFIG_SET_IS_SAVED";

export const CONFIG_SET_MESSAGE = "CONFIG_SET_MESSAGE";
