export const TEST_SET_STEP = "TEST_SET_STEP";

export const TEST_SET_MOBILE_NUMBER = "TEST_SET_MOBILE_NUMBER";

export const TEST_SAVE_MOBILE_NUMBER = "TEST_SAVE_MOBILE_NUMBER";

export const TEST_INITIATE_FETCH = "TEST_INITIATE_FETCH";

export const TEST_SET_QUESTION = "TEST_SET_QUESTION";

export const TEST_SET_LOADING = "TEST_SET_LOADING";

export const TEST_SET_SHOW_ALERT = "TEST_SET_SHOW_ALERT";

export const TEST_SET_IS_SAVED = "TEST_SET_IS_SAVED";

export const TEST_SET_MESSAGE = "TEST_SET_MESSAGE";
