export const AUTH_INITIATE_SIGNUP = "AUTH_INITIATE_SIGNUP";
export const AUTH_SIGNUP_SET_ERROR = "AUTH_SIGNUP_SET_ERROR";

export const AUTH_SET = "AUTH_SET";
export const AUTH_INITIATE_INITIAL_CHECK = "AUTH_INITIATE_INITIAL_CHECK";

export const AUTH_LOADING_START = "AUTH_LOADING_START";
export const AUTH_LOADING_END = "AUTH_LOADING_END";

export const AUTH_INITIATE_LOGOUT = "AUTH_INITIATE_LOGOUT";

export const AUTH_INITIATE_SIGNIN = "AUTH_INITIATE_SIGNIN";
export const AUTH_SIGNIN_SET_ERROR = "AUTH_SIGNIN_SET_ERROR";

