export const CATEGORY_INITIATE_STORE = "CATEGORY_INITIATE_STORE";
export const CATEGORY_INITIATE_UPDATE = "CATEGORY_INITIATE_UPDATE";

export const CATEGORY_FETCH_ALL = "CATEGORY_FETCH_ALL";
export const CATEGORY_SET_ALL = "CATEGORY_SET_ALL";

export const CATEGORY_INITIATE_DELETE = "CATEGORY_INITIATE_DELETE";

export const CATEGORY_FORM_SET_ERROR = "CATEGORY_FORM_SET_ERROR";
export const CATEGORY_FORM_SET_LOADING = "CATEGORY_FORM_SET_LOADING";

export const CATEGORY_SET_FORM_CLOSE = "CATEGORY_SET_FORM_CLOSE";
export const CATEGORY_INITIATE_FETCH_FRONT_ALL = "CATEGORY_INITIATE_FETCH_FRONT_ALL";
export const CATEGORY_SET_FRONT_ALL = "CATEGORY_SET_FRONT_ALL";
