export const CONFIG_INITIATE_FETCH = "CONFIG_INITIATE_FETCH";

export const CONFIG_SET = "CONFIG_SET";

export const CONFIG_SAVE = "CONFIG_SAVE";

export const CONFIG_SET_LOADING = "CONFIG_SET_LOADING";

export const CONFIG_SET_SHOW_ALERT = "CONFIG_SET_SHOW_ALERT";

export const CONFIG_SET_IS_SAVED = "CONFIG_SET_IS_SAVED";

export const CONFIG_SET_MESSAGE = "CONFIG_SET_MESSAGE";
