export const NEWS_LETTER_INITIATE_IS_SAVE = "NEWS_LETTER_INITIATE_IS_SAVE";
export const NEWS_LETTER_INITIATE_SAVE = "NEWS_LETTER_INITIATE_SAVE";
export const NEWS_LETTER_SET_SHOW_ALERT = "NEWS_LETTER_SET_SHOW_ALERT";
export const NEWS_LETTER_SET_IS_SAVED = "NEWS_LETTER_SET_IS_SAVED";
export const NEWS_LETTER_SET_MESSAGE = "NEWS_LETTER_SET_MESSAGE";
export const NEWS_LETTER_SET_MESSAGE_TYPE = "NEWS_LETTER_SET_MESSAGE_TYPE";
